export { default as HomePage } from './Home'
export { default as NotificationsPage } from './Notifications'
export { default as MapPage } from './Map'
export { default as SettingsPage } from './Settings'
export { default as NotFoundPage } from './NotFound'